version: '3.8'

services:
  # Judge0 Service
  judge0:
    image: judge0/judge0:1.13.0
    container_name: sheetcode-judge0
    restart: always
    privileged: true
    environment:
      - REDIS_HOST=139.59.63.141
      - REDIS_PORT=6379
      - REDIS_PASSWORD=RedisPass123!
      - POSTGRES_HOST=139.59.63.141
      - POSTGRES_PORT=5432
      - POSTGRES_USER=sheetcode_user
      - POSTGRES_PASSWORD=SecurePass123!
      - POSTGRES_DB=sheetcode_db
      - ENABLE_WAIT_RESULT=true
      - MAX_CPU_TIME_LIMIT=15
      - MAX_MEMORY_LIMIT=1024000
    ports:
      - "2358:2358"
    networks:
      - sheetcode

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: sheetcode-backend
    restart: always
    depends_on:
      - judge0
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_URL=postgresql://sheetcode_user:SecurePass123!@139.59.63.141:5432/sheetcode_db
      - JWT_SECRET=eb8143481e73cca624142ed820743e4a2bd24de84a0922cf351f4e9ca0c45695
      - FRONTEND_URL=http://139.59.63.141
      - CLOUDINARY_CLOUD_NAME=dm4mrjfyf
      - CLOUDINARY_API_KEY=563843211895523
      - CLOUDINARY_API_SECRET=cGzDqPukbFSyauOJBtc_tiKEaV4
      - JUDGE0_API_URL=http://localhost:2358
    ports:
      - "8080:8080"
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - sheetcode

networks:
  sheetcode:
    driver: bridge

volumes:
  backend_uploads: