version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: sheetcode-postgres
    restart: always
    environment:
      POSTGRES_USER: sheetcode_user
      POSTGRES_PASSWORD: SecurePass123!
      POSTGRES_DB: sheetcode_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sheetcode

  # Redis for Judge0
  redis:
    image: redis:7-alpine
    container_name: sheetcode-redis
    restart: always
    command: redis-server --requirepass RedisPass123!
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - sheetcode

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
      args:
        - VITE_API_URL=http://139.59.63.141/api/v1
    container_name: sheetcode-frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - sheetcode

networks:
  sheetcode:
    driver: bridge

volumes:
  postgres_data:
  redis_data: